// Code generated by go generate; DO NOT EDIT.
package lazyecs

import (
	"reflect"
	"unsafe"
)

// This template generates N-ary functions for the public World API, specifically
// for getting, setting, and removing multiple components at once. These functions
// (e.g., GetComponent2, SetComponent3) provide a convenient and type-safe way to
// interact with entities that have several components, abstracting away the
// underlying archetype and bitmask operations.
//
// Placeholders:
// - .N: The number of components (e.g., 2, 3).
// - .Types: The generic type parameters, e.g., "T1 any, T2 any".
// - .TypeVars: The type names themselves, e.g., "T1, T2".
// - .Vars: Variable declarations for SetComponentN, e.g., "v1 T1, v2 T2".
// - .ReturnTypes: Pointer return types for GetComponentN, e.g., "*T1, *T2".
// - .ReturnNil: A list of nil values for returns, e.g., "nil, nil".
// - .MaskCheck: The condition to check if an archetype has all the components.
// - .HasAll: A boolean check for SetComponentN, e.g., "has1 && has2".
// - .IsRemovedID: A condition to check if a component is being removed.
// GetComponent2 retrieves pointers to the 2 components of type
// (T1, T2) for the given entity.
//
// If the entity is invalid or does not have all the requested components, this
// function returns nil for all pointers.
//
// Parameters:
//   - w: The World containing the entity.
//   - e: The Entity from which to retrieve the components.
//
// Returns:
//   - Pointers to the component data (*T1, *T2), or nils if not found.
func GetComponent2[T1 any, T2 any](w *World, e Entity) (*T1, *T2) {
	if !w.IsValid(e) {
		return nil, nil
	}
	meta := w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)

	if id2 == id1 {
		panic("ecs: duplicate component types in GetComponent2")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63

	if (a.mask[i1]&(uint64(1)<<uint64(o1))) == 0 || (a.mask[i2]&(uint64(1)<<uint64(o2))) == 0 {
		return nil, nil
	}
	ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
	ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])

	return (*T1)(ptr1), (*T2)(ptr2)
}

// SetComponent2 adds or updates the 2 components (T1, T2) on the
// specified entity.
//
// If the entity does not already have all the components, this operation will
// cause the entity to move to a different archetype. If the entity is invalid,
// this function does nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
//   - v1: The component data of type T1 to set.
//   - v2: The component data of type T2 to set.
func SetComponent2[T1 any, T2 any](w *World, e Entity, v1 T1, v2 T2) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)

	if id2 == id1 {
		panic("ecs: duplicate component types in SetComponent2")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0

	if has1 && has2 {
		ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
		*(*T1)(ptr1) = v1
		ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
		*(*T2)(ptr2) = v2

		return
	}
	newMask := a.mask
	if !has1 {
		newMask.set(id1)
	}
	if !has2 {
		newMask.set(id2)
	}

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		if !has1 {
			tempSpecs[count] = compSpec{id: id1, typ: w.compIDToType[id1], size: w.compIDToSize[id1]}
			count++
		}
		if !has2 {
			tempSpecs[count] = compSpec{id: id2, typ: w.compIDToType[id2], size: w.compIDToSize[id2]}
			count++
		}

		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	ptr1 := unsafe.Pointer(uintptr(targetA.compPointers[id1]) + uintptr(newIdx)*targetA.compSizes[id1])
	*(*T1)(ptr1) = v1
	ptr2 := unsafe.Pointer(uintptr(targetA.compPointers[id2]) + uintptr(newIdx)*targetA.compSizes[id2])
	*(*T2)(ptr2) = v2

	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// RemoveComponent2 removes the 2 components (T1, T2) from the
// specified entity.
//
// This operation will cause the entity to move to a new archetype. If the
// entity is invalid or does not have all the components, this function does
// nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
func RemoveComponent2[T1 any, T2 any](w *World, e Entity) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)

	if id2 == id1 {
		panic("ecs: duplicate component types in RemoveComponent2")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0

	if !has1 && !has2 {
		return
	}
	newMask := a.mask
	newMask.unset(id1)
	newMask.unset(id2)

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			if cid == id1 || cid == id2 {
				continue
			}
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		if cid == id1 || cid == id2 {
			continue
		}
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// This template generates N-ary functions for the public World API, specifically
// for getting, setting, and removing multiple components at once. These functions
// (e.g., GetComponent2, SetComponent3) provide a convenient and type-safe way to
// interact with entities that have several components, abstracting away the
// underlying archetype and bitmask operations.
//
// Placeholders:
// - .N: The number of components (e.g., 2, 3).
// - .Types: The generic type parameters, e.g., "T1 any, T2 any".
// - .TypeVars: The type names themselves, e.g., "T1, T2".
// - .Vars: Variable declarations for SetComponentN, e.g., "v1 T1, v2 T2".
// - .ReturnTypes: Pointer return types for GetComponentN, e.g., "*T1, *T2".
// - .ReturnNil: A list of nil values for returns, e.g., "nil, nil".
// - .MaskCheck: The condition to check if an archetype has all the components.
// - .HasAll: A boolean check for SetComponentN, e.g., "has1 && has2".
// - .IsRemovedID: A condition to check if a component is being removed.
// GetComponent3 retrieves pointers to the 3 components of type
// (T1, T2, T3) for the given entity.
//
// If the entity is invalid or does not have all the requested components, this
// function returns nil for all pointers.
//
// Parameters:
//   - w: The World containing the entity.
//   - e: The Entity from which to retrieve the components.
//
// Returns:
//   - Pointers to the component data (*T1, *T2, *T3), or nils if not found.
func GetComponent3[T1 any, T2 any, T3 any](w *World, e Entity) (*T1, *T2, *T3) {
	if !w.IsValid(e) {
		return nil, nil, nil
	}
	meta := w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)

	if id2 == id1 || id3 == id1 || id3 == id2 {
		panic("ecs: duplicate component types in GetComponent3")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63

	if (a.mask[i1]&(uint64(1)<<uint64(o1))) == 0 || (a.mask[i2]&(uint64(1)<<uint64(o2))) == 0 || (a.mask[i3]&(uint64(1)<<uint64(o3))) == 0 {
		return nil, nil, nil
	}
	ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
	ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
	ptr3 := unsafe.Pointer(uintptr(a.compPointers[id3]) + uintptr(meta.index)*a.compSizes[id3])

	return (*T1)(ptr1), (*T2)(ptr2), (*T3)(ptr3)
}

// SetComponent3 adds or updates the 3 components (T1, T2, T3) on the
// specified entity.
//
// If the entity does not already have all the components, this operation will
// cause the entity to move to a different archetype. If the entity is invalid,
// this function does nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
//   - v1: The component data of type T1 to set.
//   - v2: The component data of type T2 to set.
//   - v3: The component data of type T3 to set.
func SetComponent3[T1 any, T2 any, T3 any](w *World, e Entity, v1 T1, v2 T2, v3 T3) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)

	if id2 == id1 || id3 == id1 || id3 == id2 {
		panic("ecs: duplicate component types in SetComponent3")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0
	has3 := (a.mask[i3] & (uint64(1) << uint64(o3))) != 0

	if has1 && has2 && has3 {
		ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
		*(*T1)(ptr1) = v1
		ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
		*(*T2)(ptr2) = v2
		ptr3 := unsafe.Pointer(uintptr(a.compPointers[id3]) + uintptr(meta.index)*a.compSizes[id3])
		*(*T3)(ptr3) = v3

		return
	}
	newMask := a.mask
	if !has1 {
		newMask.set(id1)
	}
	if !has2 {
		newMask.set(id2)
	}
	if !has3 {
		newMask.set(id3)
	}

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		if !has1 {
			tempSpecs[count] = compSpec{id: id1, typ: w.compIDToType[id1], size: w.compIDToSize[id1]}
			count++
		}
		if !has2 {
			tempSpecs[count] = compSpec{id: id2, typ: w.compIDToType[id2], size: w.compIDToSize[id2]}
			count++
		}
		if !has3 {
			tempSpecs[count] = compSpec{id: id3, typ: w.compIDToType[id3], size: w.compIDToSize[id3]}
			count++
		}

		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	ptr1 := unsafe.Pointer(uintptr(targetA.compPointers[id1]) + uintptr(newIdx)*targetA.compSizes[id1])
	*(*T1)(ptr1) = v1
	ptr2 := unsafe.Pointer(uintptr(targetA.compPointers[id2]) + uintptr(newIdx)*targetA.compSizes[id2])
	*(*T2)(ptr2) = v2
	ptr3 := unsafe.Pointer(uintptr(targetA.compPointers[id3]) + uintptr(newIdx)*targetA.compSizes[id3])
	*(*T3)(ptr3) = v3

	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// RemoveComponent3 removes the 3 components (T1, T2, T3) from the
// specified entity.
//
// This operation will cause the entity to move to a new archetype. If the
// entity is invalid or does not have all the components, this function does
// nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
func RemoveComponent3[T1 any, T2 any, T3 any](w *World, e Entity) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)

	if id2 == id1 || id3 == id1 || id3 == id2 {
		panic("ecs: duplicate component types in RemoveComponent3")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0
	has3 := (a.mask[i3] & (uint64(1) << uint64(o3))) != 0

	if !has1 && !has2 && !has3 {
		return
	}
	newMask := a.mask
	newMask.unset(id1)
	newMask.unset(id2)
	newMask.unset(id3)

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			if cid == id1 || cid == id2 || cid == id3 {
				continue
			}
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		if cid == id1 || cid == id2 || cid == id3 {
			continue
		}
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// This template generates N-ary functions for the public World API, specifically
// for getting, setting, and removing multiple components at once. These functions
// (e.g., GetComponent2, SetComponent3) provide a convenient and type-safe way to
// interact with entities that have several components, abstracting away the
// underlying archetype and bitmask operations.
//
// Placeholders:
// - .N: The number of components (e.g., 2, 3).
// - .Types: The generic type parameters, e.g., "T1 any, T2 any".
// - .TypeVars: The type names themselves, e.g., "T1, T2".
// - .Vars: Variable declarations for SetComponentN, e.g., "v1 T1, v2 T2".
// - .ReturnTypes: Pointer return types for GetComponentN, e.g., "*T1, *T2".
// - .ReturnNil: A list of nil values for returns, e.g., "nil, nil".
// - .MaskCheck: The condition to check if an archetype has all the components.
// - .HasAll: A boolean check for SetComponentN, e.g., "has1 && has2".
// - .IsRemovedID: A condition to check if a component is being removed.
// GetComponent4 retrieves pointers to the 4 components of type
// (T1, T2, T3, T4) for the given entity.
//
// If the entity is invalid or does not have all the requested components, this
// function returns nil for all pointers.
//
// Parameters:
//   - w: The World containing the entity.
//   - e: The Entity from which to retrieve the components.
//
// Returns:
//   - Pointers to the component data (*T1, *T2, *T3, *T4), or nils if not found.
func GetComponent4[T1 any, T2 any, T3 any, T4 any](w *World, e Entity) (*T1, *T2, *T3, *T4) {
	if !w.IsValid(e) {
		return nil, nil, nil, nil
	}
	meta := w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 {
		panic("ecs: duplicate component types in GetComponent4")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63

	if (a.mask[i1]&(uint64(1)<<uint64(o1))) == 0 || (a.mask[i2]&(uint64(1)<<uint64(o2))) == 0 || (a.mask[i3]&(uint64(1)<<uint64(o3))) == 0 || (a.mask[i4]&(uint64(1)<<uint64(o4))) == 0 {
		return nil, nil, nil, nil
	}
	ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
	ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
	ptr3 := unsafe.Pointer(uintptr(a.compPointers[id3]) + uintptr(meta.index)*a.compSizes[id3])
	ptr4 := unsafe.Pointer(uintptr(a.compPointers[id4]) + uintptr(meta.index)*a.compSizes[id4])

	return (*T1)(ptr1), (*T2)(ptr2), (*T3)(ptr3), (*T4)(ptr4)
}

// SetComponent4 adds or updates the 4 components (T1, T2, T3, T4) on the
// specified entity.
//
// If the entity does not already have all the components, this operation will
// cause the entity to move to a different archetype. If the entity is invalid,
// this function does nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
//   - v1: The component data of type T1 to set.
//   - v2: The component data of type T2 to set.
//   - v3: The component data of type T3 to set.
//   - v4: The component data of type T4 to set.
func SetComponent4[T1 any, T2 any, T3 any, T4 any](w *World, e Entity, v1 T1, v2 T2, v3 T3, v4 T4) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 {
		panic("ecs: duplicate component types in SetComponent4")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0
	has3 := (a.mask[i3] & (uint64(1) << uint64(o3))) != 0
	has4 := (a.mask[i4] & (uint64(1) << uint64(o4))) != 0

	if has1 && has2 && has3 && has4 {
		ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
		*(*T1)(ptr1) = v1
		ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
		*(*T2)(ptr2) = v2
		ptr3 := unsafe.Pointer(uintptr(a.compPointers[id3]) + uintptr(meta.index)*a.compSizes[id3])
		*(*T3)(ptr3) = v3
		ptr4 := unsafe.Pointer(uintptr(a.compPointers[id4]) + uintptr(meta.index)*a.compSizes[id4])
		*(*T4)(ptr4) = v4

		return
	}
	newMask := a.mask
	if !has1 {
		newMask.set(id1)
	}
	if !has2 {
		newMask.set(id2)
	}
	if !has3 {
		newMask.set(id3)
	}
	if !has4 {
		newMask.set(id4)
	}

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		if !has1 {
			tempSpecs[count] = compSpec{id: id1, typ: w.compIDToType[id1], size: w.compIDToSize[id1]}
			count++
		}
		if !has2 {
			tempSpecs[count] = compSpec{id: id2, typ: w.compIDToType[id2], size: w.compIDToSize[id2]}
			count++
		}
		if !has3 {
			tempSpecs[count] = compSpec{id: id3, typ: w.compIDToType[id3], size: w.compIDToSize[id3]}
			count++
		}
		if !has4 {
			tempSpecs[count] = compSpec{id: id4, typ: w.compIDToType[id4], size: w.compIDToSize[id4]}
			count++
		}

		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	ptr1 := unsafe.Pointer(uintptr(targetA.compPointers[id1]) + uintptr(newIdx)*targetA.compSizes[id1])
	*(*T1)(ptr1) = v1
	ptr2 := unsafe.Pointer(uintptr(targetA.compPointers[id2]) + uintptr(newIdx)*targetA.compSizes[id2])
	*(*T2)(ptr2) = v2
	ptr3 := unsafe.Pointer(uintptr(targetA.compPointers[id3]) + uintptr(newIdx)*targetA.compSizes[id3])
	*(*T3)(ptr3) = v3
	ptr4 := unsafe.Pointer(uintptr(targetA.compPointers[id4]) + uintptr(newIdx)*targetA.compSizes[id4])
	*(*T4)(ptr4) = v4

	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// RemoveComponent4 removes the 4 components (T1, T2, T3, T4) from the
// specified entity.
//
// This operation will cause the entity to move to a new archetype. If the
// entity is invalid or does not have all the components, this function does
// nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
func RemoveComponent4[T1 any, T2 any, T3 any, T4 any](w *World, e Entity) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 {
		panic("ecs: duplicate component types in RemoveComponent4")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0
	has3 := (a.mask[i3] & (uint64(1) << uint64(o3))) != 0
	has4 := (a.mask[i4] & (uint64(1) << uint64(o4))) != 0

	if !has1 && !has2 && !has3 && !has4 {
		return
	}
	newMask := a.mask
	newMask.unset(id1)
	newMask.unset(id2)
	newMask.unset(id3)
	newMask.unset(id4)

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			if cid == id1 || cid == id2 || cid == id3 || cid == id4 {
				continue
			}
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		if cid == id1 || cid == id2 || cid == id3 || cid == id4 {
			continue
		}
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// This template generates N-ary functions for the public World API, specifically
// for getting, setting, and removing multiple components at once. These functions
// (e.g., GetComponent2, SetComponent3) provide a convenient and type-safe way to
// interact with entities that have several components, abstracting away the
// underlying archetype and bitmask operations.
//
// Placeholders:
// - .N: The number of components (e.g., 2, 3).
// - .Types: The generic type parameters, e.g., "T1 any, T2 any".
// - .TypeVars: The type names themselves, e.g., "T1, T2".
// - .Vars: Variable declarations for SetComponentN, e.g., "v1 T1, v2 T2".
// - .ReturnTypes: Pointer return types for GetComponentN, e.g., "*T1, *T2".
// - .ReturnNil: A list of nil values for returns, e.g., "nil, nil".
// - .MaskCheck: The condition to check if an archetype has all the components.
// - .HasAll: A boolean check for SetComponentN, e.g., "has1 && has2".
// - .IsRemovedID: A condition to check if a component is being removed.
// GetComponent5 retrieves pointers to the 5 components of type
// (T1, T2, T3, T4, T5) for the given entity.
//
// If the entity is invalid or does not have all the requested components, this
// function returns nil for all pointers.
//
// Parameters:
//   - w: The World containing the entity.
//   - e: The Entity from which to retrieve the components.
//
// Returns:
//   - Pointers to the component data (*T1, *T2, *T3, *T4, *T5), or nils if not found.
func GetComponent5[T1 any, T2 any, T3 any, T4 any, T5 any](w *World, e Entity) (*T1, *T2, *T3, *T4, *T5) {
	if !w.IsValid(e) {
		return nil, nil, nil, nil, nil
	}
	meta := w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()
	t5 := reflect.TypeFor[T5]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)
	id5 := w.getCompTypeID(t5)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 || id5 == id1 || id5 == id2 || id5 == id3 || id5 == id4 {
		panic("ecs: duplicate component types in GetComponent5")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63
	i5 := id5 >> 6
	o5 := id5 & 63

	if (a.mask[i1]&(uint64(1)<<uint64(o1))) == 0 || (a.mask[i2]&(uint64(1)<<uint64(o2))) == 0 || (a.mask[i3]&(uint64(1)<<uint64(o3))) == 0 || (a.mask[i4]&(uint64(1)<<uint64(o4))) == 0 || (a.mask[i5]&(uint64(1)<<uint64(o5))) == 0 {
		return nil, nil, nil, nil, nil
	}
	ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
	ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
	ptr3 := unsafe.Pointer(uintptr(a.compPointers[id3]) + uintptr(meta.index)*a.compSizes[id3])
	ptr4 := unsafe.Pointer(uintptr(a.compPointers[id4]) + uintptr(meta.index)*a.compSizes[id4])
	ptr5 := unsafe.Pointer(uintptr(a.compPointers[id5]) + uintptr(meta.index)*a.compSizes[id5])

	return (*T1)(ptr1), (*T2)(ptr2), (*T3)(ptr3), (*T4)(ptr4), (*T5)(ptr5)
}

// SetComponent5 adds or updates the 5 components (T1, T2, T3, T4, T5) on the
// specified entity.
//
// If the entity does not already have all the components, this operation will
// cause the entity to move to a different archetype. If the entity is invalid,
// this function does nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
//   - v1: The component data of type T1 to set.
//   - v2: The component data of type T2 to set.
//   - v3: The component data of type T3 to set.
//   - v4: The component data of type T4 to set.
//   - v5: The component data of type T5 to set.
func SetComponent5[T1 any, T2 any, T3 any, T4 any, T5 any](w *World, e Entity, v1 T1, v2 T2, v3 T3, v4 T4, v5 T5) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()
	t5 := reflect.TypeFor[T5]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)
	id5 := w.getCompTypeID(t5)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 || id5 == id1 || id5 == id2 || id5 == id3 || id5 == id4 {
		panic("ecs: duplicate component types in SetComponent5")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63
	i5 := id5 >> 6
	o5 := id5 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0
	has3 := (a.mask[i3] & (uint64(1) << uint64(o3))) != 0
	has4 := (a.mask[i4] & (uint64(1) << uint64(o4))) != 0
	has5 := (a.mask[i5] & (uint64(1) << uint64(o5))) != 0

	if has1 && has2 && has3 && has4 && has5 {
		ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
		*(*T1)(ptr1) = v1
		ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
		*(*T2)(ptr2) = v2
		ptr3 := unsafe.Pointer(uintptr(a.compPointers[id3]) + uintptr(meta.index)*a.compSizes[id3])
		*(*T3)(ptr3) = v3
		ptr4 := unsafe.Pointer(uintptr(a.compPointers[id4]) + uintptr(meta.index)*a.compSizes[id4])
		*(*T4)(ptr4) = v4
		ptr5 := unsafe.Pointer(uintptr(a.compPointers[id5]) + uintptr(meta.index)*a.compSizes[id5])
		*(*T5)(ptr5) = v5

		return
	}
	newMask := a.mask
	if !has1 {
		newMask.set(id1)
	}
	if !has2 {
		newMask.set(id2)
	}
	if !has3 {
		newMask.set(id3)
	}
	if !has4 {
		newMask.set(id4)
	}
	if !has5 {
		newMask.set(id5)
	}

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		if !has1 {
			tempSpecs[count] = compSpec{id: id1, typ: w.compIDToType[id1], size: w.compIDToSize[id1]}
			count++
		}
		if !has2 {
			tempSpecs[count] = compSpec{id: id2, typ: w.compIDToType[id2], size: w.compIDToSize[id2]}
			count++
		}
		if !has3 {
			tempSpecs[count] = compSpec{id: id3, typ: w.compIDToType[id3], size: w.compIDToSize[id3]}
			count++
		}
		if !has4 {
			tempSpecs[count] = compSpec{id: id4, typ: w.compIDToType[id4], size: w.compIDToSize[id4]}
			count++
		}
		if !has5 {
			tempSpecs[count] = compSpec{id: id5, typ: w.compIDToType[id5], size: w.compIDToSize[id5]}
			count++
		}

		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	ptr1 := unsafe.Pointer(uintptr(targetA.compPointers[id1]) + uintptr(newIdx)*targetA.compSizes[id1])
	*(*T1)(ptr1) = v1
	ptr2 := unsafe.Pointer(uintptr(targetA.compPointers[id2]) + uintptr(newIdx)*targetA.compSizes[id2])
	*(*T2)(ptr2) = v2
	ptr3 := unsafe.Pointer(uintptr(targetA.compPointers[id3]) + uintptr(newIdx)*targetA.compSizes[id3])
	*(*T3)(ptr3) = v3
	ptr4 := unsafe.Pointer(uintptr(targetA.compPointers[id4]) + uintptr(newIdx)*targetA.compSizes[id4])
	*(*T4)(ptr4) = v4
	ptr5 := unsafe.Pointer(uintptr(targetA.compPointers[id5]) + uintptr(newIdx)*targetA.compSizes[id5])
	*(*T5)(ptr5) = v5

	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// RemoveComponent5 removes the 5 components (T1, T2, T3, T4, T5) from the
// specified entity.
//
// This operation will cause the entity to move to a new archetype. If the
// entity is invalid or does not have all the components, this function does
// nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
func RemoveComponent5[T1 any, T2 any, T3 any, T4 any, T5 any](w *World, e Entity) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()
	t5 := reflect.TypeFor[T5]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)
	id5 := w.getCompTypeID(t5)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 || id5 == id1 || id5 == id2 || id5 == id3 || id5 == id4 {
		panic("ecs: duplicate component types in RemoveComponent5")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63
	i5 := id5 >> 6
	o5 := id5 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0
	has3 := (a.mask[i3] & (uint64(1) << uint64(o3))) != 0
	has4 := (a.mask[i4] & (uint64(1) << uint64(o4))) != 0
	has5 := (a.mask[i5] & (uint64(1) << uint64(o5))) != 0

	if !has1 && !has2 && !has3 && !has4 && !has5 {
		return
	}
	newMask := a.mask
	newMask.unset(id1)
	newMask.unset(id2)
	newMask.unset(id3)
	newMask.unset(id4)
	newMask.unset(id5)

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			if cid == id1 || cid == id2 || cid == id3 || cid == id4 || cid == id5 {
				continue
			}
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		if cid == id1 || cid == id2 || cid == id3 || cid == id4 || cid == id5 {
			continue
		}
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// This template generates N-ary functions for the public World API, specifically
// for getting, setting, and removing multiple components at once. These functions
// (e.g., GetComponent2, SetComponent3) provide a convenient and type-safe way to
// interact with entities that have several components, abstracting away the
// underlying archetype and bitmask operations.
//
// Placeholders:
// - .N: The number of components (e.g., 2, 3).
// - .Types: The generic type parameters, e.g., "T1 any, T2 any".
// - .TypeVars: The type names themselves, e.g., "T1, T2".
// - .Vars: Variable declarations for SetComponentN, e.g., "v1 T1, v2 T2".
// - .ReturnTypes: Pointer return types for GetComponentN, e.g., "*T1, *T2".
// - .ReturnNil: A list of nil values for returns, e.g., "nil, nil".
// - .MaskCheck: The condition to check if an archetype has all the components.
// - .HasAll: A boolean check for SetComponentN, e.g., "has1 && has2".
// - .IsRemovedID: A condition to check if a component is being removed.
// GetComponent6 retrieves pointers to the 6 components of type
// (T1, T2, T3, T4, T5, T6) for the given entity.
//
// If the entity is invalid or does not have all the requested components, this
// function returns nil for all pointers.
//
// Parameters:
//   - w: The World containing the entity.
//   - e: The Entity from which to retrieve the components.
//
// Returns:
//   - Pointers to the component data (*T1, *T2, *T3, *T4, *T5, *T6), or nils if not found.
func GetComponent6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any](w *World, e Entity) (*T1, *T2, *T3, *T4, *T5, *T6) {
	if !w.IsValid(e) {
		return nil, nil, nil, nil, nil, nil
	}
	meta := w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()
	t5 := reflect.TypeFor[T5]()
	t6 := reflect.TypeFor[T6]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)
	id5 := w.getCompTypeID(t5)
	id6 := w.getCompTypeID(t6)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 || id5 == id1 || id5 == id2 || id5 == id3 || id5 == id4 || id6 == id1 || id6 == id2 || id6 == id3 || id6 == id4 || id6 == id5 {
		panic("ecs: duplicate component types in GetComponent6")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63
	i5 := id5 >> 6
	o5 := id5 & 63
	i6 := id6 >> 6
	o6 := id6 & 63

	if (a.mask[i1]&(uint64(1)<<uint64(o1))) == 0 || (a.mask[i2]&(uint64(1)<<uint64(o2))) == 0 || (a.mask[i3]&(uint64(1)<<uint64(o3))) == 0 || (a.mask[i4]&(uint64(1)<<uint64(o4))) == 0 || (a.mask[i5]&(uint64(1)<<uint64(o5))) == 0 || (a.mask[i6]&(uint64(1)<<uint64(o6))) == 0 {
		return nil, nil, nil, nil, nil, nil
	}
	ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
	ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
	ptr3 := unsafe.Pointer(uintptr(a.compPointers[id3]) + uintptr(meta.index)*a.compSizes[id3])
	ptr4 := unsafe.Pointer(uintptr(a.compPointers[id4]) + uintptr(meta.index)*a.compSizes[id4])
	ptr5 := unsafe.Pointer(uintptr(a.compPointers[id5]) + uintptr(meta.index)*a.compSizes[id5])
	ptr6 := unsafe.Pointer(uintptr(a.compPointers[id6]) + uintptr(meta.index)*a.compSizes[id6])

	return (*T1)(ptr1), (*T2)(ptr2), (*T3)(ptr3), (*T4)(ptr4), (*T5)(ptr5), (*T6)(ptr6)
}

// SetComponent6 adds or updates the 6 components (T1, T2, T3, T4, T5, T6) on the
// specified entity.
//
// If the entity does not already have all the components, this operation will
// cause the entity to move to a different archetype. If the entity is invalid,
// this function does nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
//   - v1: The component data of type T1 to set.
//   - v2: The component data of type T2 to set.
//   - v3: The component data of type T3 to set.
//   - v4: The component data of type T4 to set.
//   - v5: The component data of type T5 to set.
//   - v6: The component data of type T6 to set.
func SetComponent6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any](w *World, e Entity, v1 T1, v2 T2, v3 T3, v4 T4, v5 T5, v6 T6) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()
	t5 := reflect.TypeFor[T5]()
	t6 := reflect.TypeFor[T6]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)
	id5 := w.getCompTypeID(t5)
	id6 := w.getCompTypeID(t6)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 || id5 == id1 || id5 == id2 || id5 == id3 || id5 == id4 || id6 == id1 || id6 == id2 || id6 == id3 || id6 == id4 || id6 == id5 {
		panic("ecs: duplicate component types in SetComponent6")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63
	i5 := id5 >> 6
	o5 := id5 & 63
	i6 := id6 >> 6
	o6 := id6 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0
	has3 := (a.mask[i3] & (uint64(1) << uint64(o3))) != 0
	has4 := (a.mask[i4] & (uint64(1) << uint64(o4))) != 0
	has5 := (a.mask[i5] & (uint64(1) << uint64(o5))) != 0
	has6 := (a.mask[i6] & (uint64(1) << uint64(o6))) != 0

	if has1 && has2 && has3 && has4 && has5 && has6 {
		ptr1 := unsafe.Pointer(uintptr(a.compPointers[id1]) + uintptr(meta.index)*a.compSizes[id1])
		*(*T1)(ptr1) = v1
		ptr2 := unsafe.Pointer(uintptr(a.compPointers[id2]) + uintptr(meta.index)*a.compSizes[id2])
		*(*T2)(ptr2) = v2
		ptr3 := unsafe.Pointer(uintptr(a.compPointers[id3]) + uintptr(meta.index)*a.compSizes[id3])
		*(*T3)(ptr3) = v3
		ptr4 := unsafe.Pointer(uintptr(a.compPointers[id4]) + uintptr(meta.index)*a.compSizes[id4])
		*(*T4)(ptr4) = v4
		ptr5 := unsafe.Pointer(uintptr(a.compPointers[id5]) + uintptr(meta.index)*a.compSizes[id5])
		*(*T5)(ptr5) = v5
		ptr6 := unsafe.Pointer(uintptr(a.compPointers[id6]) + uintptr(meta.index)*a.compSizes[id6])
		*(*T6)(ptr6) = v6

		return
	}
	newMask := a.mask
	if !has1 {
		newMask.set(id1)
	}
	if !has2 {
		newMask.set(id2)
	}
	if !has3 {
		newMask.set(id3)
	}
	if !has4 {
		newMask.set(id4)
	}
	if !has5 {
		newMask.set(id5)
	}
	if !has6 {
		newMask.set(id6)
	}

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		if !has1 {
			tempSpecs[count] = compSpec{id: id1, typ: w.compIDToType[id1], size: w.compIDToSize[id1]}
			count++
		}
		if !has2 {
			tempSpecs[count] = compSpec{id: id2, typ: w.compIDToType[id2], size: w.compIDToSize[id2]}
			count++
		}
		if !has3 {
			tempSpecs[count] = compSpec{id: id3, typ: w.compIDToType[id3], size: w.compIDToSize[id3]}
			count++
		}
		if !has4 {
			tempSpecs[count] = compSpec{id: id4, typ: w.compIDToType[id4], size: w.compIDToSize[id4]}
			count++
		}
		if !has5 {
			tempSpecs[count] = compSpec{id: id5, typ: w.compIDToType[id5], size: w.compIDToSize[id5]}
			count++
		}
		if !has6 {
			tempSpecs[count] = compSpec{id: id6, typ: w.compIDToType[id6], size: w.compIDToSize[id6]}
			count++
		}

		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	ptr1 := unsafe.Pointer(uintptr(targetA.compPointers[id1]) + uintptr(newIdx)*targetA.compSizes[id1])
	*(*T1)(ptr1) = v1
	ptr2 := unsafe.Pointer(uintptr(targetA.compPointers[id2]) + uintptr(newIdx)*targetA.compSizes[id2])
	*(*T2)(ptr2) = v2
	ptr3 := unsafe.Pointer(uintptr(targetA.compPointers[id3]) + uintptr(newIdx)*targetA.compSizes[id3])
	*(*T3)(ptr3) = v3
	ptr4 := unsafe.Pointer(uintptr(targetA.compPointers[id4]) + uintptr(newIdx)*targetA.compSizes[id4])
	*(*T4)(ptr4) = v4
	ptr5 := unsafe.Pointer(uintptr(targetA.compPointers[id5]) + uintptr(newIdx)*targetA.compSizes[id5])
	*(*T5)(ptr5) = v5
	ptr6 := unsafe.Pointer(uintptr(targetA.compPointers[id6]) + uintptr(newIdx)*targetA.compSizes[id6])
	*(*T6)(ptr6) = v6

	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}

// RemoveComponent6 removes the 6 components (T1, T2, T3, T4, T5, T6) from the
// specified entity.
//
// This operation will cause the entity to move to a new archetype. If the
// entity is invalid or does not have all the components, this function does
// nothing.
//
// Parameters:
//   - w: The World where the entity resides.
//   - e: The Entity to modify.
func RemoveComponent6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any](w *World, e Entity) {
	if !w.IsValid(e) {
		return
	}
	meta := &w.metas[e.ID]
	t1 := reflect.TypeFor[T1]()
	t2 := reflect.TypeFor[T2]()
	t3 := reflect.TypeFor[T3]()
	t4 := reflect.TypeFor[T4]()
	t5 := reflect.TypeFor[T5]()
	t6 := reflect.TypeFor[T6]()

	id1 := w.getCompTypeID(t1)
	id2 := w.getCompTypeID(t2)
	id3 := w.getCompTypeID(t3)
	id4 := w.getCompTypeID(t4)
	id5 := w.getCompTypeID(t5)
	id6 := w.getCompTypeID(t6)

	if id2 == id1 || id3 == id1 || id3 == id2 || id4 == id1 || id4 == id2 || id4 == id3 || id5 == id1 || id5 == id2 || id5 == id3 || id5 == id4 || id6 == id1 || id6 == id2 || id6 == id3 || id6 == id4 || id6 == id5 {
		panic("ecs: duplicate component types in RemoveComponent6")
	}
	a := w.archetypes[meta.archetypeIndex]
	i1 := id1 >> 6
	o1 := id1 & 63
	i2 := id2 >> 6
	o2 := id2 & 63
	i3 := id3 >> 6
	o3 := id3 & 63
	i4 := id4 >> 6
	o4 := id4 & 63
	i5 := id5 >> 6
	o5 := id5 & 63
	i6 := id6 >> 6
	o6 := id6 & 63

	has1 := (a.mask[i1] & (uint64(1) << uint64(o1))) != 0
	has2 := (a.mask[i2] & (uint64(1) << uint64(o2))) != 0
	has3 := (a.mask[i3] & (uint64(1) << uint64(o3))) != 0
	has4 := (a.mask[i4] & (uint64(1) << uint64(o4))) != 0
	has5 := (a.mask[i5] & (uint64(1) << uint64(o5))) != 0
	has6 := (a.mask[i6] & (uint64(1) << uint64(o6))) != 0

	if !has1 && !has2 && !has3 && !has4 && !has5 && !has6 {
		return
	}
	newMask := a.mask
	newMask.unset(id1)
	newMask.unset(id2)
	newMask.unset(id3)
	newMask.unset(id4)
	newMask.unset(id5)
	newMask.unset(id6)

	var targetA *archetype
	if idx, ok := w.maskToArcIndex[newMask]; ok {
		targetA = w.archetypes[idx]
	} else {
		var tempSpecs [MaxComponentTypes]compSpec
		count := 0
		for _, cid := range a.compOrder {
			if cid == id1 || cid == id2 || cid == id3 || cid == id4 || cid == id5 || cid == id6 {
				continue
			}
			tempSpecs[count] = compSpec{id: cid, typ: w.compIDToType[cid], size: w.compIDToSize[cid]}
			count++
		}
		specs := tempSpecs[:count]
		targetA = w.getOrCreateArchetype(newMask, specs)
	}
	newIdx := targetA.size
	targetA.entityIDs[newIdx] = e
	targetA.size++
	for _, cid := range a.compOrder {
		if cid == id1 || cid == id2 || cid == id3 || cid == id4 || cid == id5 || cid == id6 {
			continue
		}
		src := unsafe.Pointer(uintptr(a.compPointers[cid]) + uintptr(meta.index)*a.compSizes[cid])
		dst := unsafe.Pointer(uintptr(targetA.compPointers[cid]) + uintptr(newIdx)*targetA.compSizes[cid])
		memCopy(dst, src, a.compSizes[cid])
	}
	w.removeFromArchetype(a, meta)
	meta.archetypeIndex = targetA.index
	meta.index = newIdx
}
