name: "Benchmark"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  benchmark:
    name: "Run benchmarks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: "Run benchmarks"
        run: go test -benchmem -run=^$ -bench . . | tee benchmark_results.txt

      - name: "Upload benchmark results"
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmark_results.txt