name: "Benchmark"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    name: "Run benchmarks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.25.1"

      - name: "Run benchmarks"
        run: go test -benchmem -run=^$ -bench . .
