name: "Benchmark"

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: "Run benchmarks and commit results"
    runs-on: ubuntu-latest
    # Prevent workflow run from re-triggering itself
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: "Run benchmarks"
        run: go test -benchmem -run=^$ -bench . . | tee benchmark-results.txt

      - name: "Commit and push benchmark results"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add benchmark-results.txt
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "docs: Update benchmark results"
            git push
          fi